=== unknown-wq/minecolonies/libs/blockui/26.3/src/main/resources/assets/blockui/gui/block_ui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:simpleType name="align">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TOP_LEFT"/>
            <xs:enumeration value="TOP_MIDDLE"/>
            <xs:enumeration value="TOP_RIGHT"/>
            <xs:enumeration value="MIDDLE_LEFT"/>
            <xs:enumeration value="MIDDLE"/>
            <xs:enumeration value="MIDDLE_RIGHT"/>
            <xs:enumeration value="BOTTOM_LEFT"/>
            <xs:enumeration value="BOTTOM_MIDDLE"/>
            <xs:enumeration value="BOTTOM_RIGHT"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Parsers.SCALED splits on "\\s*[,\\s]\\s*", so a comma separates just as well as a space. -->
    <xs:simpleType name="sizePair">
        <xs:restriction base="xs:string">
            <xs:pattern value="([-+]?\d+)(%|px)?(\s*[,\s]\s*([-+]?\d+)(%|px)?)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fixedSizePair">
        <xs:restriction base="xs:string">
            <xs:pattern value="(-)?\d+(\s*[,\s]\s*(-)?\d+)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit" type="xs:string"/>
        <xs:attribute name="size" type="sizePair"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="blurBackground" type="xs:boolean"/>
        <xs:attribute name="pause" type="xs:boolean"/>
        <xs:attribute name="type" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="VANILLA"/>
                    <xs:enumeration value="FULLSCREEN"/>
                    <xs:enumeration value="FULLSCREEN_VANILLA"/>
                    <xs:enumeration value="FIXED"/>
                    <xs:enumeration value="FIXED_VANILLA"/>
                    <xs:enumeration value="OVERSIZED"/>
                    <xs:enumeration value="OVERSIZED_VANILLA"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id" type="xs:string"/>

        <xs:attribute name="align" type="align"/>
        <xs:attribute name="size" type="sizePair"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="pos" type="sizePair"/>
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>
        <xs:attribute name="tooltip" type="xs:string"/>
        <xs:attribute name="onHoverId" type="xs:string"/>

        <xs:attribute name="style" type="xs:string"/>
        <xs:attribute name="cursor" type="xs:string"/>
    </xs:complexType>

    <!-- Abstract text element -->
    <xs:complexType name="textElementType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="textscale" type="xs:string"/>
                <xs:attribute name="textalign" type="align"/>
                <xs:attribute name="color" type="xs:string"/> <!-- overrides all textcolors-->
                <xs:attribute name="textcolor" type="xs:string"/>
                <xs:attribute name="texthovercolor" type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow" type="xs:boolean"/>
                <xs:attribute name="wrap" type="xs:boolean"/>
                <xs:attribute name="linespace" type="xs:integer"/>
                <xs:attribute name="text" type="xs:string"/>
                <xs:attribute name="label" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Scroll view basic attributes and contents -->
    <xs:complexType name="scrollViewType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="childspacing" type="xs:integer"/>
                <xs:attribute name="scrollbarOffset" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout" type="layoutElementType"/>
            <xs:element name="view" type="viewType"/>
            <!-- Loader registers "overlay" for OverlayView; it was missing here until 26.3. -->
            <xs:element name="overlay" type="viewType"/>
            <xs:element name="zoomdragview" type="zoomDragType"/>
            <xs:element name="group" type="groupType"/>
            <xs:element name="scrollgroup" type="scrollViewType"/>
            <xs:element name="list" type="listType"/>
            <xs:element name="button" type="buttonType"/>
            <xs:element name="toggle" type="toggleType"/>
            <xs:element name="text" type="textType"/>
            <xs:element name="input" type="inputType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="imagerepeat" type="imageRepeatType"/>
            <xs:element name="gradient" type="gradientType"/>
            <xs:element name="box" type="boxType"/>
            <xs:element name="itemicon" type="itemIconType"/>
            <xs:element name="entityicon" type="entityIconType"/>
            <xs:element name="switch" type="switchType"/>
            <xs:element name="dropdown" type="dropdownType"/>
            <xs:element name="checkbox" type="checkboxType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
                <xs:attribute name="endless" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="scrollViewType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>

                <xs:attribute name="emptytext" type="xs:string"/>
                <xs:attribute name="emptyscale" type="xs:string"/>
                <xs:attribute name="emptycolor" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="textElementType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="highlight" type="xs:string"/>
                <xs:attribute name="disabled" type="xs:string"/>
                <xs:attribute name="textoffset" type="fixedSizePair"/>
                <xs:attribute name="textbox" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <text> -->
    <xs:complexType name="textType">
        <xs:complexContent>
            <xs:extension base="textElementType"></xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
                <xs:attribute name="nbt" type="xs:string"/>
                <xs:attribute name="properties" type="xs:string"/>
                <xs:attribute name="renderItemDecorations" type="xs:boolean" default="true"/>
                <xs:attribute name="alwaysAddBlockStateTooltip" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
        <!-- TODO:
            <xs:assert test="(@nbt and not(@properties)) or (not(@nbt) and @properties)"/>
        -->
    </xs:complexType>

    <!-- <entityicon> -->
    <xs:complexType name="entityIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="entity" type="xs:string"/>
                <xs:attribute name="count" type="xs:integer"/>
                <xs:attribute name="yaw" type="xs:float"/>
                <xs:attribute name="pitch" type="xs:float"/>
                <xs:attribute name="head" type="xs:float"/>
                <xs:attribute name="renderState" type="xs:string"/>
                <xs:attribute name="transformation" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <toggle> -->
    <xs:complexType name="toggleType">
        <xs:complexContent>
            <xs:extension base="buttonType">
                <xs:attribute name="options" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="fixedSizePair"/>
                <xs:attribute name="imagesize" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="imageRepeatType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="textureoffset" type="fixedSizePair"/>
                <xs:attribute name="texturesize" type="fixedSizePair"/>
                <xs:attribute name="repeatoffset" type="fixedSizePair"/>
                <xs:attribute name="repeatsize" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <gradient> -->
    <xs:complexType name="gradientType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="gradientstart" type="xs:string"/>
                <xs:attribute name="gradientend" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="textContent" type="xs:string"/>
                <xs:attribute name="maxlength" type="xs:integer"/>
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow" type="xs:boolean"/>
                <xs:attribute name="tab" type="xs:string"/>
                <!-- TextFieldVanilla reads these three; they were missing here until 26.3. -->
                <xs:attribute name="background" type="xs:boolean"/>
                <xs:attribute name="backgroundOuter" type="xs:string"/>
                <xs:attribute name="backgroundInner" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!--
        <dropdown>
        DropDownList hands its own PaneParams to both a ButtonImage and a ScrollingList, so it accepts every
        attribute either of those reads. It used to be declared here as a bare pane, which made a perfectly valid
        layout fail validation on, for instance, textscale=.
    -->
    <xs:complexType name="dropdownType">
        <xs:complexContent>
            <xs:extension base="buttonType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
                <xs:attribute name="maxContentHeight" type="xs:integer"/>
                <xs:attribute name="dropDownSize" type="fixedSizePair"/>
                <xs:attribute name="childspacing" type="xs:integer"/>
                <xs:attribute name="scrollbarOffset" type="fixedSizePair"/>
                <xs:attribute name="emptytext" type="xs:string"/>
                <xs:attribute name="emptyscale" type="xs:string"/>
                <xs:attribute name="emptycolor" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <zoom> -->
    <xs:complexType name="zoomDragType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="dragfactor" type="xs:double"/>
                <xs:attribute name="dragenabled" type="xs:boolean"/>
                <xs:attribute name="zoomfactor" type="xs:double"/>
                <xs:attribute name="zoomenabled" type="xs:boolean"/>
                <xs:attribute name="minscale" type="xs:double"/>
                <xs:attribute name="maxscale" type="xs:double"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <checkbox> -->
    <xs:complexType name="checkboxType">
        <xs:complexContent>
            <xs:extension base="buttonType">
                <xs:attribute name="checkmark" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== unknown-wq/minecolonies/libs/blockui/26.3/src/main/resources/assets/blockui/gui/showcase_inherit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    The two ways one layout can pull in another. Opened by -Dblockui.testgui=inherit.

    inherit= runs another window's contents against this window before this window's own size= and children are
    applied; <layout source="…"/> appends another file's children to whatever view the tag sits in. Both end up in
    Loader#createFromXMLFile, and both are how a consuming mod avoids copying a common header into thirty layouts —
    which makes them exactly the paths that quietly stop working when the loader is touched.

    Reading the screen: the green fragment box must appear three times — once at the very top left because it was
    inherited, and twice more where the two <layout> tags are.
-->
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="block_ui.xsd"
        inherit="blockui:gui/showcase_common.xml"
        size="900 460" type="FULLSCREEN_VANILLA" lightbox="true">

    <text pos="4 44" size="890 11" textcolor="#FFFFD966" textscale="1.1" text="BlockUI include paths — blockui:gui/showcase_inherit.xml"/>
    <text pos="4 58" size="890 20" wrap="true" textscale="0.85" textcolor="lightgray"
          text="The box at the top left came from inherit=. It was parsed before this window applied its own size, so it sits at 0,0 in the window's own coordinates."/>

    <text pos="4 84" size="890 10" textcolor="aqua" textscale="0.9" text="&lt;layout&gt; inside a plain View"/>
    <view id="include_in_view" pos="4 96" size="440 44">
        <layout source="blockui:gui/showcase_common.xml"/>
    </view>

    <text pos="452 84" size="440 10" textcolor="aqua" textscale="0.9" text="&lt;layout&gt; inside a Box inside a Group"/>
    <group id="include_group" pos="452 96" size="440 60" spacing="2">
        <box size="440 46" color="#FF8888FF" linewidth="1">
            <view pos="2 2" size="434 42">
                <layout source="blockui:gui/showcase_common.xml"/>
            </view>
        </box>
        <text size="440 10" textscale="0.75" textcolor="lightgray" text="…three container levels between the window and the include"/>
    </group>

    <text pos="4 164" size="890 10" textcolor="aqua" textscale="0.9" text="the same fragment inside a scrolling list row"/>
    <list id="include_rows" pos="4 176" size="890 130" childspacing="4">
        <view size="874 44">
            <layout source="blockui:gui/showcase_common.xml"/>
            <text id="row_index" pos="306 16" size="560 10" textscale="0.75" textcolor="orange"/>
        </view>
    </list>

    <text pos="4 312" size="890 20" wrap="true" textscale="0.85" textcolor="lightgray"
          text="Every copy above is a separate pane tree built from one cached PaneParams. Editing the fragment and reloading resources (F3+T) must change all of them at once."/>

    <box id="inherit_notes" pos="4 338" size="890 116" color="#FFB36AFF" linewidth="1">
        <text pos="4 3" size="882 10" textcolor="aqua" textscale="0.9" text="what this exercises in Loader"/>
        <text pos="4 16" size="882 12" textscale="0.8" textcolor="ivory" text="• the xml cache is keyed per resource, so one parse feeds every include"/>
        <text pos="4 30" size="882 12" textscale="0.8" textcolor="ivory" text="• PaneParams instances are reused across windows — the property cache must not leak a value from one host into another"/>
        <text pos="4 44" size="882 12" textscale="0.8" textcolor="ivory" text="• &lt;layout&gt; returns null from createFromPaneParams and must not be treated as a pane"/>
        <text pos="4 58" size="882 12" textscale="0.8" textcolor="ivory" text="• inherit= recurses into createFromXMLFile with the window itself as the parent"/>
        <text pos="4 72" size="882 12" textscale="0.8" textcolor="ivory" text="• a row template that contains a &lt;layout&gt; is re-instantiated per row"/>
        <text pos="4 86" size="882 24" wrap="true" textscale="0.8" textcolor="lightgray"
              text="If any of those breaks, the fragment disappears from one of the three places above rather than crashing, which is why this file states how many copies to expect."/>
    </box>
</window>

=== unknown-wq/minecolonies/libs/structurize/26.3/src/main/resources/assets/structurize/gui/layoutmanipulation.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ldtteam/BlockUI/version/main/src/main/resources/assets/blockui/gui/block_ui.xsd"
        size="420 240" pause="false" type="OVERSIZED_VANILLA" lightbox="false">

    <text id="tip" size="200 50" pos="150 100" color="white" label="$(structurize.gui.manipulation.info)" visible="false"/>

    <view size="48 64" pos="370 100" id="manipulator">
        <button id="rotateLeft" source="structurize:textures/gui/buildtool/rotateleft.png" size="16" pos="0 0"/>
        <button id="up" source="structurize:textures/gui/buildtool/up.png" size="16" pos="16 0"/>
        <button id="rotateRight" source="structurize:textures/gui/buildtool/rotateright.png" size="16" pos="32 0"/>
        <button id="left" source="structurize:textures/gui/buildtool/left.png" size="16" pos="0 16"/>
        <button id="mirror" source="structurize:textures/gui/buildtool/mirror.png" size="16" pos="16 16"/>
        <button id="right" source="structurize:textures/gui/buildtool/right.png" size="16" pos="32 16"/>
        <button id="minus" source="structurize:textures/gui/buildtool/minus.png" size="16" pos="0 32"/>
        <button id="down" source="structurize:textures/gui/buildtool/down.png" size="16" pos="16 32"/>
        <button id="plus" source="structurize:textures/gui/buildtool/plus.png" size="16" pos="32 32"/>
        <image id="rotation" size="16" pos="96 0" source="minecraft:missingno"/>
    </view>

    <list size="188 100" pos="5 113" id="settinglist" visible="false">
        <view size="100% 20">
            <text size="150 17" pos="0 0" id="label"/>
            <button id="switch" source="structurize:textures/gui/builderhut/builder_button_very_small.png" size="29 15" pos="150 0" textcolor="black" texthovercolor="gray"/>
            <input id="set_input" size="29 15" pos="150 0"/>
        </view>
    </list>

    <list size="100 80" pos="160 80" id="placement" visible="false">
        <button id="type" source="structurize:textures/gui/buildtool/button_medium.png" size="86 17" pos="0 0" textcolor="black" texthovercolor="gray"/>
    </list>

    <button id="confirm" source="structurize:textures/gui/buildtool/confirm.png" size="30" pos="300 213"/>
    <button id="cancel" source="structurize:textures/gui/buildtool/cancel.png" size="30" pos="90 213"/>

    <button id="settings" source="structurize:textures/gui/buildtool/settings.png" size="30" pos="0 213"/>
    <button id="contents" source="structurize:textures/gui/buildtool/paste.png" size="32 32" pos="30 212" tooltip="$(com.ldtteam.structurize.gui.scantool.showres)" visible="false"/>
</window>
